### ISSUE TITLE
Minor glitch in display

### ISSUE THREAD

**Issue by jolle-c** [bfad/lspec#2]
Minor observation. When I run a test it does not end with a new line. Thus it will look like this:

jolle$ lspec tests/zoo.spec.inc 
.

Finished in 0.103695 seconds
1 test, 0 failuresjolle:lasso jolle$ 

That is a bit confusing and not as pretty as could be.

**Comment by bfad** [comment]
Interesting. I'm seeing a new line at the end when I run it in my shell (zsh), but not when I run it under the bash shell. Will investigate further to see what I can find.

**Comment by bfad** [comment]
Fixed in commit 5a7cdcf4133510389c5e14ad247ee124cd69a869
